/**
 * @license
 * Copyright 2026 Kai-Orion & Sandlada
 * SPDX-License-Identifier: MIT
 */

/**
 * 0-indexed character source range within a document.
 */
export interface SourceRange {
    startLine: number
    startCol: number
    endLine: number
    endCol: number
}

/**
 * Metadata representing a state schema defined via defineSchema(...).
 */
export interface SchemaMeta {
    /** Schema variable name (e.g. 'ButtonSchema', 'BadgeSchema') */
    name: string
    /** Whether the schema is 2D (array of orthogonal dimensions) */
    is2D: boolean
    /** Orthogonal state dimensions (e.g. [['small', 'large'], ['selected', 'unselected']]) */
    dimensions: string[][]
    /** Flat array of all unique state names across all dimensions */
    states: string[]
    /** Flat array of all unique state names across all dimensions (alias) */
    flatStates: string[]
    /** Valid Cartesian product state combinations */
    validCombinations: string[][]
    /** Total number of valid state combinations */
    combinationCount: number
    /** Total number of valid state combinations (alias) */
    count: number
    /** Source code location range */
    range?: SourceRange
}

/**
 * Metadata representing a forwarded token bridge mapping to a child component.
 */
export interface ForwardedTokenBridgeMeta {
    targetPrefix: string
    cleanKey: string
    parentKey: string
    targetDefKeys?: readonly string[]
    state?: string
    targetExpandedKey?: string
}

/**
 * Metadata for an individual token declaration in a component definition.
 */
export interface TokenValueMeta {
    /** Token key name without prefix (e.g. 'container-color', 'container-shape-start-start') */
    key: string
    /** Alias for key */
    name?: string
    /** True if the token value was defined as an array tuple */
    isTuple: boolean
    /** True if the token value was defined as a state record object */
    isRecord?: boolean
    /** True if generated by expandShape / expandPadding / expandTypescale */
    isExpanded?: boolean
    /** Type of expander if isExpanded is true */
    expanderType?: 'shape' | 'padding' | 'typescale'
    /** Expander call source expression (e.g. "expandShape('container')(Shape.Full)") */
    expanderSource?: string
    /** List of state names present on this token */
    states?: string[]
    /** State names alias */
    stateNames?: string[]
    /** State name to value mapping (e.g. { enabled: 'Color.Primary', hovered: 'Color.PrimaryHover' }) */
    stateMap?: Record<string, string>
    /** Raw source expression string */
    rawValue?: string
    /** Raw tuple elements if isTuple is true */
    rawTuple?: string[]
    /** Raw state values array for tuple elements */
    rawStates?: (string | null | undefined)[]
    /** Record values mapping if defined as record object */
    recordValues?: Record<string, string>
    /** True if this token originated from a forwardTokens(...) spread */
    isForwarded?: boolean
    /** Bridge metadata if isForwarded is true */
    bridgeMeta?: ForwardedTokenBridgeMeta
    /** Dimension mismatch metadata if tuple length doesn't match schema states */
    dimensionMismatch?: {
        expected: number
        actual: number
    }
    /** Source code location range */
    range?: SourceRange
}

/**
 * Metadata for a child component forwarded via orwardTokens(...).
 */
export interface ForwardedChildMeta {
    /** Target child definition name (e.g. 'IconDefinition') */
    targetDefinitionName: string
    /** Target CSS variable prefix (e.g. '--mdc-icon') */
    targetPrefix: string
    /** Child prefix alias */
    childPrefix?: string
    /** Parent namespace used (e.g. 'icon') */
    namespace: string
    /** Mapping of child token key to parent namespaced key */
    tokenMap?: Record<string, string>
    /** Detailed token metadata per forwarded token */
    tokens: Record<string, any>
    /** Source code location range */
    range?: SourceRange
}

/**
 * Metadata for a state trigger declared via mapStateTriggers(...) or defaults.
 */
export interface StateTriggerMeta {
    /** State identifier name (e.g. 'selected', 'hovered', 'small') */
    state: string
    /** Target element context: 'host' for :host(...) wrapper, 'self' for current anchor element */
    target: 'host' | 'self'
    /** Selector modifier string (e.g. '[selected]', ':hover', '.small') */
    selector: string
    /** Selector modifier alias */
    modifier?: string
    /** Source origin */
    source?: 'mapStateTriggers' | 'heuristic' | string
    /** Raw trigger expression */
    rawExpression?: string
    /** True if explicitly mapped in mapStateTriggers, false if inferred via default heuristics */
    isCustom?: boolean
    /** Source code location range */
    range?: SourceRange
}

/**
 * Aggregate metadata model extracted from a *.definition.ts file.
 */
export interface DefinitionMeta {
    /** Exported definition name (e.g. 'ButtonDefinition') */
    name: string
    /** Source file path */
    filePath?: string
    /** Primary schema name if bound via curried createStyleDefinition(Schema) */
    schemaName?: string
    /** Primary schema metadata */
    schema?: SchemaMeta
    /** Map of all schema definitions in the file */
    schemas: Map<string, SchemaMeta>
    /** Map of own token definitions (including forwarded parent-namespaced tokens) */
    ownTokens: Map<string, TokenValueMeta>
    /** Map of forwarded child definitions */
    forwarded: Map<string, ForwardedChildMeta>
    /** Map of registered or inferred state triggers */
    stateTriggers: Map<string, StateTriggerMeta>
    /** Spread expressions that could not be statically resolved (e.g. `...factory(...)` calls) */
    unresolvedSpreads?: string[]
    /** Source code location range */
    range?: SourceRange
}

/**
 * Aggregate result of analyzing a whole *.definition.ts file: every definition
 * plus every `XxxVariants` dictionary mapping variant names to definitions.
 */
export interface DefinitionFileAnalysis {
    /** All parsed definitions by export name, in source order */
    definitions: Map<string, DefinitionMeta>
    /** Variant dictionary name -> member definition names */
    variants: Map<string, string[]>
}

/**
 * Location of a token reference in a stylesheet.
 */
export interface TokenUsageLocation {
    token: string // e.g. '--_container-color'
    cleanKey: string // e.g. 'container-color'
    range: SourceRange
    fullMatch: string // e.g. 'var(--_container-color)'
    fallback?: string // e.g. '#ffffff' if invalid fallback is present
}

/**
 * Metadata for a used private token (--_*).
 */
export interface UsedPrivateToken {
    token: string // e.g. '--_container-color' or '--_enabled-container-color'
    cleanKey: string // e.g. 'container-color'
    isTuple: boolean
    states: string[]
    rawValue?: string
    locations?: TokenUsageLocation[]
}

/**
 * Metadata for a used child bridge token (--mdc-<child>-*).
 */
export interface UsedChildBridgeToken {
    token: string // e.g. '--mdc-icon-enabled-color'
    targetName: string // e.g. 'IconDefinition'
    targetPrefix: string // e.g. '--mdc-icon'
    sourceVarName: string // e.g. '--mdc-button-enabled-icon-color'
    fallbackValue?: string
    locations?: TokenUsageLocation[]
}

/**
 * Metadata for stringifyTokens declaration.
 */
export interface TokenRecordDeclaration {
    line: number
    varName: string
    definitionName: string
    prefix?: string
    range?: SourceRange
}

/**
 * Metadata for stringifyTokens call site.
 */
export interface StringifyTokensCallMeta {
    line: number
    varName?: string
    definitionName: string
    prefix: string
    includePublicVars?: boolean
    selector?: string
    range: SourceRange
}

/**
 * Metadata for overrideTokens declaration.
 */
export interface OverrideDeclaration {
    line: number
    targetName: string
    prefix: string
    selector?: string
    props?: Record<string, string>
    range?: SourceRange
}

/**
 * Metadata for an ATRule instance in a stylesheet.
 */
export interface ATRuleUsageMeta {
    /** ATRule type */
    type?: 'anchor' | 'when' | 'variant' | 'size' | 'slot' | 'slotted' | 'elevation' | 'layer' | 'media' | 'supports' | 'container' | 'keyframes' | string
    /** ATRule name */
    name: '@anchor' | '@when' | '@variant' | '@size' | '@slot' | '@slotted' | '@elevation' | string
    /** Header argument (e.g. '.container', 'selected', 'small') */
    argument: string
    /** Header string */
    header?: string
    /** Parameter alias */
    param?: string
    /** Source range */
    range: SourceRange
    /** Block content */
    content?: string
}

/**
 * Diagnostic issue codes.
 */
export type DiagnosticCode = 'MDC001' | 'MDC002' | 'MDC003' | 'MDC004'

/**
 * Diagnostic issue representation.
 */
export interface DiagnosticIssue {
    code: DiagnosticCode
    message: string
    severity: 'error' | 'warning' | 'info'
    range: SourceRange
    token: string
    quickFix?: {
        title: string
        replacement: string
        range: SourceRange
    }
}

/**
 * Complete analysis result for a *.style.ts stylesheet file.
 */
export interface StylesheetAnalysis {
    styleVarName: string // e.g. 'ButtonStyles'
    definitionName: string // e.g. 'ButtonDefinition'
    definitionNames?: string[] // all definitions involved
    definitionFilePath?: string
    declarationLine: number // 0-indexed line of xport const XxxStyles
    createStyleSheetLine?: number // 0-indexed line of createStyleSheet(...)
    stringifyTokensLine?: number
    tokenRecords?: TokenRecordDeclaration[]
    stringifyTokenCalls?: StringifyTokensCallMeta[]
    stateTriggers?: StateTriggerMeta[]
    overrides?: OverrideDeclaration[]
    atRules?: ATRuleUsageMeta[]
    usedPrivateTokens: UsedPrivateToken[]
    usedChildBridgeTokens: UsedChildBridgeToken[]
    /** Set of normalized clean token keys referenced in the stylesheet */
    usedTokens: Set<string>
    /** Declared tokens from definition not present in usedTokens */
    unusedTokens: string[]
    totalDefinitionTokens: number
    coveragePercent: number
    rawCssText: string
    allUsages: TokenUsageLocation[]
    diagnostics?: DiagnosticIssue[]
}
