/**
 * @license
 * Copyright 2025 Kai-Orion & Sandlada
 * SPDX-License-Identifier: MIT
 */
import { ElevationLevel, Shape, State, Typescale } from '@sandlada/mdk'
import { Color } from '../utils/tokens/theme'
import { createStyleDefinition } from '../utils/tokens/create-style-definition'

const shared = {
    'extra-small-container-shape-round-start-start': Shape.Full,
    'extra-small-container-shape-round-start-end': Shape.Full,
    'extra-small-container-shape-round-end-start': Shape.Full,
    'extra-small-container-shape-round-end-end': Shape.Full,
    'small-container-shape-round-start-start': Shape.Full,
    'small-container-shape-round-start-end': Shape.Full,
    'small-container-shape-round-end-start': Shape.Full,
    'small-container-shape-round-end-end': Shape.Full,
    'medium-container-shape-round-start-start': Shape.Full,
    'medium-container-shape-round-start-end': Shape.Full,
    'medium-container-shape-round-end-start': Shape.Full,
    'medium-container-shape-round-end-end': Shape.Full,
    'large-container-shape-round-start-start': Shape.Full,
    'large-container-shape-round-start-end': Shape.Full,
    'large-container-shape-round-end-start': Shape.Full,
    'large-container-shape-round-end-end': Shape.Full,
    'extra-large-container-shape-round-start-start': Shape.Full,
    'extra-large-container-shape-round-start-end': Shape.Full,
    'extra-large-container-shape-round-end-start': Shape.Full,
    'extra-large-container-shape-round-end-end': Shape.Full,

    'extra-small-container-shape-square-start-start': Shape.Medium,
    'extra-small-container-shape-square-start-end': Shape.Medium,
    'extra-small-container-shape-square-end-start': Shape.Medium,
    'extra-small-container-shape-square-end-end': Shape.Medium,
    'small-container-shape-square-start-start': Shape.Medium,
    'small-container-shape-square-start-end': Shape.Medium,
    'small-container-shape-square-end-start': Shape.Medium,
    'small-container-shape-square-end-end': Shape.Medium,
    'medium-container-shape-square-start-start': Shape.Large,
    'medium-container-shape-square-start-end': Shape.Large,
    'medium-container-shape-square-end-start': Shape.Large,
    'medium-container-shape-square-end-end': Shape.Large,
    'large-container-shape-square-start-start': Shape.ExtraLarge,
    'large-container-shape-square-start-end': Shape.ExtraLarge,
    'large-container-shape-square-end-start': Shape.ExtraLarge,
    'large-container-shape-square-end-end': Shape.ExtraLarge,
    'extra-large-container-shape-square-start-start': Shape.ExtraLarge,
    'extra-large-container-shape-square-start-end': Shape.ExtraLarge,
    'extra-large-container-shape-square-end-start': Shape.ExtraLarge,
    'extra-large-container-shape-square-end-end': Shape.ExtraLarge,

    'extra-small-container-shape-pressed-morph-start-start': Shape.Small,
    'extra-small-container-shape-pressed-morph-start-end': Shape.Small,
    'extra-small-container-shape-pressed-morph-end-start': Shape.Small,
    'extra-small-container-shape-pressed-morph-end-end': Shape.Small,
    'small-container-shape-pressed-morph-start-start': Shape.Small,
    'small-container-shape-pressed-morph-start-end': Shape.Small,
    'small-container-shape-pressed-morph-end-start': Shape.Small,
    'small-container-shape-pressed-morph-end-end': Shape.Small,
    'medium-container-shape-pressed-morph-start-start': Shape.Medium,
    'medium-container-shape-pressed-morph-start-end': Shape.Medium,
    'medium-container-shape-pressed-morph-end-start': Shape.Medium,
    'medium-container-shape-pressed-morph-end-end': Shape.Medium,
    'large-container-shape-pressed-morph-start-start': Shape.Large,
    'large-container-shape-pressed-morph-start-end': Shape.Large,
    'large-container-shape-pressed-morph-end-start': Shape.Large,
    'large-container-shape-pressed-morph-end-end': Shape.Large,
    'extra-large-container-shape-pressed-morph-start-start': Shape.Large,
    'extra-large-container-shape-pressed-morph-start-end': Shape.Large,
    'extra-large-container-shape-pressed-morph-end-start': Shape.Large,
    'extra-large-container-shape-pressed-morph-end-end': Shape.Large,

    'extra-small-container-shape-round-toggle-selected-start-start': Shape.Medium,
    'extra-small-container-shape-round-toggle-selected-start-end': Shape.Medium,
    'extra-small-container-shape-round-toggle-selected-end-start': Shape.Medium,
    'extra-small-container-shape-round-toggle-selected-end-end': Shape.Medium,
    'small-container-shape-round-toggle-selected-start-start': Shape.Medium,
    'small-container-shape-round-toggle-selected-start-end': Shape.Medium,
    'small-container-shape-round-toggle-selected-end-start': Shape.Medium,
    'small-container-shape-round-toggle-selected-end-end': Shape.Medium,
    'medium-container-shape-round-toggle-selected-start-start': Shape.Large,
    'medium-container-shape-round-toggle-selected-start-end': Shape.Large,
    'medium-container-shape-round-toggle-selected-end-start': Shape.Large,
    'medium-container-shape-round-toggle-selected-end-end': Shape.Large,
    'large-container-shape-round-toggle-selected-start-start': Shape.ExtraLarge,
    'large-container-shape-round-toggle-selected-start-end': Shape.ExtraLarge,
    'large-container-shape-round-toggle-selected-end-start': Shape.ExtraLarge,
    'large-container-shape-round-toggle-selected-end-end': Shape.ExtraLarge,
    'extra-large-container-shape-round-toggle-selected-start-start': Shape.ExtraLarge,
    'extra-large-container-shape-round-toggle-selected-start-end': Shape.ExtraLarge,
    'extra-large-container-shape-round-toggle-selected-end-start': Shape.ExtraLarge,
    'extra-large-container-shape-round-toggle-selected-end-end': Shape.ExtraLarge,

    'extra-small-container-shape-square-toggle-selected-start-start': Shape.Full,
    'extra-small-container-shape-square-toggle-selected-start-end': Shape.Full,
    'extra-small-container-shape-square-toggle-selected-end-start': Shape.Full,
    'extra-small-container-shape-square-toggle-selected-end-end': Shape.Full,
    'small-container-shape-square-toggle-selected-start-start': Shape.Full,
    'small-container-shape-square-toggle-selected-start-end': Shape.Full,
    'small-container-shape-square-toggle-selected-end-start': Shape.Full,
    'small-container-shape-square-toggle-selected-end-end': Shape.Full,
    'medium-container-shape-square-toggle-selected-start-start': Shape.Full,
    'medium-container-shape-square-toggle-selected-start-end': Shape.Full,
    'medium-container-shape-square-toggle-selected-end-start': Shape.Full,
    'medium-container-shape-square-toggle-selected-end-end': Shape.Full,
    'large-container-shape-square-toggle-selected-start-start': Shape.Full,
    'large-container-shape-square-toggle-selected-start-end': Shape.Full,
    'large-container-shape-square-toggle-selected-end-start': Shape.Full,
    'large-container-shape-square-toggle-selected-end-end': Shape.Full,
    'extra-large-container-shape-square-toggle-selected-start-start': Shape.Full,
    'extra-large-container-shape-square-toggle-selected-start-end': Shape.Full,
    'extra-large-container-shape-square-toggle-selected-end-start': Shape.Full,
    'extra-large-container-shape-square-toggle-selected-end-end': Shape.Full,

    'extra-small-container-height'        : `32px`,
    'extra-small-outline-width'           : `1px`,
    'extra-small-label-font'              : Typescale.LabelLarge.Font,
    'extra-small-label-line-height'       : Typescale.LabelLarge.LineHeight,
    'extra-small-label-size'              : Typescale.LabelLarge.FontSize,
    'extra-small-label-tracking'          : Typescale.LabelLarge.Tracking,
    'extra-small-label-weight'            : Typescale.LabelLarge.FontWeight,
    'extra-small-icon-size'               : `20px`,
    'extra-small-leading-space'           : `12px`,
    'extra-small-between-icon-label-space': `8px`,
    'extra-small-trailing-space'          : `12px`,

    'small-container-height'        : `40px`,
    'small-outline-width'           : `1px`,
    'small-label-font'              : Typescale.LabelLarge.Font,
    'small-label-line-height'       : Typescale.LabelLarge.LineHeight,
    'small-label-size'              : Typescale.LabelLarge.FontSize,
    'small-label-tracking'          : Typescale.LabelLarge.Tracking,
    'small-label-weight'            : Typescale.LabelLarge.FontWeight,
    'small-icon-size'               : `20px`,
    'small-leading-space'           : `16px`,
    'small-between-icon-label-space': `8px`,
    'small-trailing-space'          : `16px`,

    'medium-container-height'        : `56px`,
    'medium-outline-width'           : `1px`,
    'medium-label-font'              : Typescale.TitleMedium.Font,
    'medium-label-line-height'       : Typescale.TitleMedium.LineHeight,
    'medium-label-size'              : Typescale.TitleMedium.FontSize,
    'medium-label-tracking'          : Typescale.TitleMedium.Tracking,
    'medium-label-weight'            : Typescale.TitleMedium.FontWeight,
    'medium-icon-size'               : `24px`,
    'medium-leading-space'           : `24px`,
    'medium-between-icon-label-space': `8px`,
    'medium-trailing-space'          : `24px`,

    'large-container-height'        : `96px`,
    'large-outline-width'           : `2px`,
    'large-label-font'              : Typescale.HeadlineSmall.Font,
    'large-label-line-height'       : Typescale.HeadlineSmall.LineHeight,
    'large-label-size'              : Typescale.HeadlineSmall.FontSize,
    'large-label-tracking'          : Typescale.HeadlineSmall.Tracking,
    'large-label-weight'            : Typescale.HeadlineSmall.FontWeight,
    'large-icon-size'               : `32px`,
    'large-leading-space'           : `48px`,
    'large-between-icon-label-space': `12px`,
    'large-trailing-space'          : `48px`,

    'extra-large-container-height'        : `136px`,
    'extra-large-outline-width'           : `3px`,
    'extra-large-label-font'              : Typescale.HeadlineLarge.Font,
    'extra-large-label-line-height'       : Typescale.HeadlineLarge.LineHeight,
    'extra-large-label-size'              : Typescale.HeadlineLarge.FontSize,
    'extra-large-label-tracking'          : Typescale.HeadlineLarge.Tracking,
    'extra-large-label-weight'            : Typescale.HeadlineLarge.FontWeight,
    'extra-large-icon-size'               : `40px`,
    'extra-large-leading-space'           : `64px`,
    'extra-large-between-icon-label-space': `16px`,
    'extra-large-trailing-space'          : `64px`,
} as const

export const ElevatedButtonDefinition = createStyleDefinition({
    ...shared,

    // Enabled
    'container-color'                  : Color.SurfaceContainerLow,
    'container-color-toggle-unselected': Color.SurfaceContainerLow,
    'container-color-toggle-selected'  : Color.Primary,
    'container-shadow-color'           : Color.Shadow,
    'container-elevation'              : ElevationLevel.Level1,
    'label-color'                      : Color.Primary,
    'label-color-toggle-unselected'    : Color.Primary,
    'label-color-toggle-selected'      : Color.OnPrimary,
    'icon-color'                       : Color.Primary,
    'icon-color-toggle-unselected'     : Color.Primary,
    'icon-color-toggle-selected'       : Color.OnPrimary,

    // Disabled
    'disabled-container-color'                  : Color.OnSurface,
    'disabled-container-color-toggle-unselected': Color.OnSurface,
    'disabled-container-color-toggle-selected'  : Color.OnSurface,
    'disabled-container-opacity'                : `0.1`,
    'disabled-container-shadow-color'           : Color.Shadow,
    'disabled-container-elevation'              : ElevationLevel.Level0,
    'disabled-label-color'                      : Color.OnSurface,
    'disabled-label-color-toggle-unselected'    : Color.OnSurface,
    'disabled-label-color-toggle-selected'      : Color.OnSurface,
    'disabled-label-opacity'                    : `0.38`,
    'disabled-icon-color'                       : Color.OnSurface,
    'disabled-icon-color-toggle-unselected'     : Color.OnSurface,
    'disabled-icon-color-toggle-selected'       : Color.OnSurface,
    'disabled-icon-opacity'                     : `0.38`,

    // Hovered
    'hovered-state-layer-color'                  : Color.Primary,
    'hovered-state-layer-color-toggle-unselected': Color.Primary,
    'hovered-state-layer-color-toggle-selected'  : Color.OnPrimary,
    'hovered-state-layer-opacity'                : State.HoveredStateLayerOpacity,
    'hovered-container-color'                    : Color.SurfaceContainerLow,
    'hovered-container-color-toggle-unselected'  : Color.SurfaceContainerLow,
    'hovered-container-color-toggle-selected'    : Color.Primary,
    'hovered-container-shadow-color'             : Color.Shadow,
    'hovered-container-elevation'                : ElevationLevel.Level1,
    'hovered-label-color'                        : Color.Primary,
    'hovered-label-color-toggle-unselected'      : Color.Primary,
    'hovered-label-color-toggle-selected'        : Color.OnPrimary,
    'hovered-icon-color'                         : Color.Primary,
    'hovered-icon-color-toggle-unselected'       : Color.Primary,
    'hovered-icon-color-toggle-selected'         : Color.OnPrimary,

    // Focused
    'focused-state-layer-color'                  : Color.Primary,
    'focused-state-layer-color-toggle-unselected': Color.Primary,
    'focused-state-layer-color-toggle-selected'  : Color.OnPrimary,
    'focused-state-layer-opacity'                : State.FocusedStateLayerOpacity,
    'focused-container-color'                    : Color.SurfaceContainerLow,
    'focused-container-color-toggle-unselected'  : Color.SurfaceContainerLow,
    'focused-container-color-toggle-selected'    : Color.Primary,
    'focused-container-shadow-color'             : Color.Shadow,
    'focused-container-elevation'                : ElevationLevel.Level1,
    'focused-label-color'                        : Color.Primary,
    'focused-label-color-toggle-unselected'      : Color.Primary,
    'focused-label-color-toggle-selected'        : Color.OnPrimary,
    'focused-icon-color'                         : Color.Primary,
    'focused-icon-color-toggle-unselected'       : Color.Primary,
    'focused-icon-color-toggle-selected'         : Color.OnPrimary,

    // Pressed
    'pressed-state-layer-color'                  : Color.Primary,
    'pressed-state-layer-color-toggle-unselected': Color.Primary,
    'pressed-state-layer-color-toggle-selected'  : Color.OnPrimary,
    'pressed-state-layer-opacity'                : State.PressedStateLayerOpacity,
    'pressed-container-color'                    : Color.SurfaceContainerLow,
    'pressed-container-color-toggle-unselected'  : Color.SurfaceContainerLow,
    'pressed-container-color-toggle-selected'    : Color.Primary,
    'pressed-container-shadow-color'             : Color.Shadow,
    'pressed-container-elevation'                : ElevationLevel.Level1,
    'pressed-label-color'                        : Color.Primary,
    'pressed-label-color-toggle-unselected'      : Color.Primary,
    'pressed-label-color-toggle-selected'        : Color.OnPrimary,
    'pressed-icon-color'                         : Color.Primary,
    'pressed-icon-color-toggle-unselected'       : Color.Primary,
    'pressed-icon-color-toggle-selected'         : Color.OnPrimary,
})

export const FilledButtonDefinition = createStyleDefinition({
    ...shared,

    // Enabled
    'container-color'                  : Color.Primary,
    'container-color-toggle-unselected': Color.SurfaceContainer,
    'container-color-toggle-selected'  : Color.Primary,
    'container-shadow-color'           : Color.Shadow,
    'container-elevation'              : ElevationLevel.Level0,
    'label-color'                      : Color.OnPrimary,
    'label-color-toggle-unselected'    : Color.OnSurfaceVariant,
    'label-color-toggle-selected'      : Color.OnPrimary,
    'icon-color'                       : Color.OnPrimary,
    'icon-color-toggle-unselected'     : Color.OnSurfaceVariant,
    'icon-color-toggle-selected'       : Color.OnPrimary,

    // Disabled
    'disabled-container-color'                  : Color.OnSurface,
    'disabled-container-color-toggle-unselected': Color.OnSurface,
    'disabled-container-color-toggle-selected'  : Color.OnSurface,
    'disabled-container-shadow-color'           : Color.Shadow,
    'disabled-container-opacity'                : `0.1`,
    'disabled-container-elevation'              : ElevationLevel.Level0,
    'disabled-label-color'                      : Color.OnSurface,
    'disabled-label-color-toggle-unselected'    : Color.OnSurface,
    'disabled-label-color-toggle-selected'      : Color.OnSurface,
    'disabled-label-opacity'                    : `0.38`,
    'disabled-icon-color'                       : Color.OnSurface,
    'disabled-icon-color-toggle-unselected'     : Color.OnSurface,
    'disabled-icon-color-toggle-selected'       : Color.OnSurface,
    'disabled-icon-opacity'                     : `0.38`,

    // Hovered
    'hovered-state-layer-color'                  : Color.OnPrimary,
    'hovered-state-layer-color-toggle-unselected': Color.OnSurfaceVariant,
    'hovered-state-layer-color-toggle-selected'  : Color.OnPrimary,
    'hovered-state-layer-opacity'                : State.HoveredStateLayerOpacity,
    'hovered-container-color'                    : Color.Primary,
    'hovered-container-color-toggle-unselected'  : Color.SurfaceContainer,
    'hovered-container-color-toggle-selected'    : Color.Primary,
    'hovered-container-shadow-color'             : Color.Shadow,
    'hovered-label-color'                        : Color.OnPrimary,
    'hovered-label-color-toggle-unselected'      : Color.OnSurfaceVariant,
    'hovered-label-color-toggle-selected'        : Color.OnPrimary,
    'hovered-icon-color'                         : Color.OnPrimary,
    'hovered-icon-color-toggle-unselected'       : Color.OnSurfaceVariant,
    'hovered-icon-color-toggle-selected'         : Color.OnPrimary,

    // Focused
    'focused-state-layer-color'                  : Color.OnPrimary,
    'focused-state-layer-color-toggle-unselected': Color.OnSurfaceVariant,
    'focused-state-layer-color-toggle-selected'  : Color.OnPrimary,
    'focused-state-layer-opacity'                : State.FocusedStateLayerOpacity,
    'focused-container-color'                    : Color.Primary,
    'focused-container-color-toggle-unselected'  : Color.SurfaceContainer,
    'focused-container-color-toggle-selected'    : Color.Primary,
    'focused-container-shadow-color'             : Color.Shadow,
    'focused-container-elevation'                : ElevationLevel.Level0,
    'focused-label-color'                        : Color.OnPrimary,
    'focused-label-color-toggle-unselected'      : Color.OnSurfaceVariant,
    'focused-label-color-toggle-selected'        : Color.OnPrimary,
    'focused-icon-color'                         : Color.OnPrimary,
    'focused-icon-color-toggle-unselected'       : Color.OnSurfaceVariant,
    'focused-icon-color-toggle-selected'         : Color.OnPrimary,

    // Pressed
    'pressed-state-layer-color'                  : Color.OnPrimary,
    'pressed-state-layer-color-toggle-unselected': Color.OnSurfaceVariant,
    'pressed-state-layer-color-toggle-selected'  : Color.OnPrimary,
    'pressed-state-layer-opacity'                : State.PressedStateLayerOpacity,
    'pressed-container-color'                    : Color.Primary,
    'pressed-container-color-toggle-unselected'  : Color.SurfaceContainer,
    'pressed-container-color-toggle-selected'    : Color.Primary,
    'pressed-container-shadow-color'             : Color.Shadow,
    'pressed-container-elevation'                : ElevationLevel.Level0,
    'pressed-label-color'                        : Color.OnPrimary,
    'pressed-label-color-toggle-unselected'      : Color.OnSurfaceVariant,
    'pressed-label-color-toggle-selected'        : Color.OnPrimary,
    'pressed-icon-color'                         : Color.OnPrimary,
    'pressed-icon-color-toggle-unselected'       : Color.OnSurfaceVariant,
    'pressed-icon-color-toggle-selected'         : Color.OnPrimary,
})

export const FilledTonalButtonDefinition = createStyleDefinition({
    ...shared,

    // Enabled
    'container-color'                  : Color.SecondaryContainer,
    'container-color-toggle-unselected': Color.SecondaryContainer,
    'container-color-toggle-selected'  : Color.Secondary,
    'container-shadow-color'           : Color.Shadow,
    'container-elevation'              : ElevationLevel.Level0,
    'label-color'                      : Color.OnSecondaryContainer,
    'label-color-toggle-unselected'    : Color.OnSecondaryContainer,
    'label-color-toggle-selected'      : Color.OnSecondary,
    'icon-color'                       : Color.OnSecondaryContainer,
    'icon-color-toggle-unselected'     : Color.OnSecondaryContainer,
    'icon-color-toggle-selected'       : Color.OnSecondary,

    // Disabled
    'disabled-container-color'                  : Color.OnSurface,
    'disabled-container-color-toggle-unselected': Color.OnSurface,
    'disabled-container-color-toggle-selected'  : Color.OnSurface,
    'disabled-container-shadow-color'           : Color.Shadow,
    'disabled-container-opacity'                : `0.1`,
    'disabled-container-elevation'              : ElevationLevel.Level0,
    'disabled-label-color'                      : Color.OnSurface,
    'disabled-label-color-toggle-unselected'    : Color.OnSurface,
    'disabled-label-color-toggle-selected'      : Color.OnSurface,
    'disabled-label-opacity'                    : `0.38`,
    'disabled-icon-color'                       : Color.OnSurface,
    'disabled-icon-color-toggle-unselected'     : Color.OnSurface,
    'disabled-icon-color-toggle-selected'       : Color.OnSurface,
    'disabled-icon-opacity'                     : `0.38`,

    // Hovered
    'hovered-state-layer-color'                  : Color.OnSecondaryContainer,
    'hovered-state-layer-color-toggle-unselected': Color.OnSecondaryContainer,
    'hovered-state-layer-color-toggle-selected'  : Color.OnSecondary,
    'hovered-state-layer-opacity'                : State.HoveredStateLayerOpacity,
    'hovered-container-color'                    : Color.SecondaryContainer,
    'hovered-container-color-toggle-unselected'  : Color.SecondaryContainer,
    'hovered-container-color-toggle-selected'    : Color.Secondary,
    'hovered-container-shadow-color'             : Color.Shadow,
    'hovered-container-elevation'                : ElevationLevel.Level0,
    'hovered-label-color'                        : Color.OnSecondaryContainer,
    'hovered-label-color-toggle-unselected'      : Color.OnSecondaryContainer,
    'hovered-label-color-toggle-selected'        : Color.OnSecondary,
    'hovered-icon-color'                         : Color.OnSecondaryContainer,
    'hovered-icon-color-toggle-unselected'       : Color.OnSecondaryContainer,
    'hovered-icon-color-toggle-selected'         : Color.OnSecondary,

    // Focused
    'focused-state-layer-color'                  : Color.OnSecondaryContainer,
    'focused-state-layer-color-toggle-unselected': Color.OnSecondaryContainer,
    'focused-state-layer-color-toggle-selected'  : Color.OnSecondary,
    'focused-state-layer-opacity'                : State.FocusedStateLayerOpacity,
    'focused-container-color'                    : Color.SecondaryContainer,
    'focused-container-color-toggle-unselected'  : Color.SecondaryContainer,
    'focused-container-color-toggle-selected'    : Color.Secondary,
    'focused-container-shadow-color'             : Color.Shadow,
    'focused-container-elevation'                : ElevationLevel.Level0,
    'focused-label-color'                        : Color.OnSecondaryContainer,
    'focused-label-color-toggle-unselected'      : Color.OnSecondaryContainer,
    'focused-label-color-toggle-selected'        : Color.OnSecondary,
    'focused-icon-color'                         : Color.OnSecondaryContainer,
    'focused-icon-color-toggle-unselected'       : Color.OnSecondaryContainer,
    'focused-icon-color-toggle-selected'         : Color.OnSecondary,

    // Pressed
    'pressed-state-layer-color'                  : Color.OnSecondaryContainer,
    'pressed-state-layer-color-toggle-unselected': Color.OnSecondaryContainer,
    'pressed-state-layer-color-toggle-selected'  : Color.OnSecondary,
    'pressed-state-layer-opacity'                : State.PressedStateLayerOpacity,
    'pressed-container-color'                    : Color.SecondaryContainer,
    'pressed-container-color-toggle-unselected'  : Color.SecondaryContainer,
    'pressed-container-color-toggle-selected'    : Color.Secondary,
    'pressed-container-shadow-color'             : Color.Shadow,
    'pressed-container-elevation'                : ElevationLevel.Level0,
    'pressed-label-color'                        : Color.OnSecondaryContainer,
    'pressed-label-color-toggle-unselected'      : Color.OnSecondaryContainer,
    'pressed-label-color-toggle-selected'        : Color.OnSecondary,
    'pressed-icon-color'                         : Color.OnSecondaryContainer,
    'pressed-icon-color-toggle-unselected'       : Color.OnSecondaryContainer,
    'pressed-icon-color-toggle-selected'         : Color.OnSecondary,
})

export const OutlinedButtonDefinition = createStyleDefinition({
    ...shared,

    // Enabled
    'outline-color'                    : Color.OutlineVariant,
    'outline-color-toggle-unselected'  : Color.OutlineVariant,
    'outline-color-toggle-selected'    : `transparent`,
    'container-color'                  : `transparent`,
    'container-color-toggle-unselected': `transparent`,
    'container-color-toggle-selected'  : Color.InverseSurface,
    'label-color'                      : Color.OnSurfaceVariant,
    'label-color-toggle-unselected'    : Color.OnSurfaceVariant,
    'label-color-toggle-selected'      : Color.InverseOnSurface,
    'icon-color'                       : Color.OnSurfaceVariant,
    'icon-color-toggle-unselected'     : Color.OnSurfaceVariant,
    'icon-color-toggle-selected'       : Color.InverseOnSurface,

    // Disabled
    'disabled-outline-color'                    : Color.OutlineVariant,
    'disabled-outline-color-toggle-unselected'  : Color.OutlineVariant,
    'disabled-outline-color-toggle-selected'    : `transparent`,
    'disabled-container-color'                  : Color.OnSurface,
    'disabled-container-color-toggle-unselected': Color.OnSurface,
    'disabled-container-color-toggle-selected'  : Color.OnSurface,
    'disabled-container-opacity'                : `0.1`,
    'disabled-label-color'                      : Color.OnSurface,
    'disabled-label-color-toggle-unselected'    : Color.OnSurface,
    'disabled-label-color-toggle-selected'      : Color.OnSurface,
    'disabled-label-opacity'                    : `0.38`,
    'disabled-icon-color'                       : Color.OnSurface,
    'disabledicon-color-toggle-unselected'      : Color.OnSurface,
    'disabledicon-color-toggle-selected'        : Color.OnSurface,
    'disabled-icon-opacity'                     : `0.38`,

    // Hovered
    'hovered-state-layer-color'                  : Color.OnSurfaceVariant,
    'hovered-state-layer-color-toggle-unselected': Color.OnSurfaceVariant,
    'hovered-state-layer-color-toggle-selected'  : Color.InverseOnSurface,
    'hovered-state-layer-opacity'                : State.HoveredStateLayerOpacity,
    'hovered-outline-color'                      : Color.OutlineVariant,
    'hovered-outline-color-toggle-unselected'    : Color.OutlineVariant,
    'hovered-outline-color-toggle-selected'      : `transparent`,
    'hovered-container-color'                    : `transparent`,
    'hovered-container-color-toggle-unselected'  : `transparent`,
    'hovered-container-color-toggle-selected'    : Color.InverseSurface,
    'hovered-label-color'                        : Color.OnSurfaceVariant,
    'hovered-label-color-toggle-unselected'      : Color.OnSurfaceVariant,
    'hovered-label-color-toggle-selected'        : Color.InverseOnSurface,
    'hovered-icon-color'                         : Color.OnSurfaceVariant,
    'hovered-icon-color-toggle-unselected'       : Color.OnSurfaceVariant,
    'hovered-icon-color-toggle-selected'         : Color.InverseOnSurface,

    // Focused
    'focused-state-layer-color'                  : Color.OnSurfaceVariant,
    'focused-state-layer-color-toggle-unselected': Color.OnSurfaceVariant,
    'focused-state-layer-color-toggle-selected'  : Color.InverseOnSurface,
    'focused-state-layer-opacity'                : State.FocusedStateLayerOpacity,
    'focused-outline-color'                      : Color.OutlineVariant,
    'focused-outline-color-toggle-unselected'    : Color.OutlineVariant,
    'focused-outline-color-toggle-selected'      : `transparent`,
    'focused-container-color'                    : `transparent`,
    'focused-container-color-toggle-unselected'  : `transparent`,
    'focused-container-color-toggle-selected'    : Color.InverseSurface,
    'focused-label-color'                        : Color.OnSurfaceVariant,
    'focused-label-color-toggle-unselected'      : Color.OnSurfaceVariant,
    'focused-label-color-toggle-selected'        : Color.InverseOnSurface,
    'focused-icon-color'                         : Color.OnSurfaceVariant,
    'focused-icon-color-toggle-unselected'       : Color.OnSurfaceVariant,
    'focused-icon-color-toggle-selected'         : Color.InverseOnSurface,

    // Pressed
    'pressed-state-layer-color'                  : Color.OnSurfaceVariant,
    'pressed-state-layer-color-toggle-unselected': Color.OnSurfaceVariant,
    'pressed-state-layer-color-toggle-selected'  : Color.InverseOnSurface,
    'pressed-state-layer-opacity'                : State.PressedStateLayerOpacity,
    'pressed-outline-color'                      : Color.OutlineVariant,
    'pressed-outline-color-toggle-unselected'    : Color.OutlineVariant,
    'pressed-outline-color-toggle-selected'      : `transparent`,
    'pressed-container-color'                    : `transparent`,
    'pressed-container-color-toggle-unselected'  : `transparent`,
    'pressed-container-color-toggle-selected'    : Color.InverseSurface,
    'pressed-label-color'                        : Color.OnSurfaceVariant,
    'pressed-label-color-toggle-unselected'      : Color.OnSurfaceVariant,
    'pressed-label-color-toggle-selected'        : Color.InverseOnSurface,
    'pressed-icon-color'                         : Color.OnSurfaceVariant,
    'pressed-icon-color-toggle-unselected'       : Color.OnSurfaceVariant,
    'pressed-icon-color-toggle-selected'         : Color.InverseOnSurface,
})

export const TextButtonDefinition = createStyleDefinition({
    ...shared,

    // Enabled
    'container-color'                  : `transparent`,
    'container-color-toggle-unselected': `transparent`,
    'container-color-toggle-selected'  : `transparent`,
    'label-color'                      : Color.Primary,
    'label-color-toggle-unselected'    : Color.Primary,
    'label-color-toggle-selected'      : Color.Primary,
    'icon-color'                       : Color.Primary,
    'icon-color-toggle-unselected'     : Color.Primary,
    'icon-color-toggle-selected'       : Color.Primary,

    // Disabled
    'disabled-container-color'                  : Color.OnSurface,
    'disabled-container-color-toggle-unselected': Color.OnSurface,
    'disabled-container-color-toggle-selected'  : Color.OnSurface,
    'disabled-container-opacity'                : `0.1`,
    'disabled-label-color'                      : Color.OnSurface,
    'disabled-label-color-toggle-unselected'    : Color.OnSurface,
    'disabled-label-color-toggle-selected'      : Color.OnSurface,
    'disabled-label-opacity'                    : `0.38`,
    'disabled-icon-color'                       : Color.OnSurface,
    'disabled-icon-color-toggle-unselected'     : Color.OnSurface,
    'disabled-icon-color-toggle-selected'       : Color.OnSurface,
    'disabled-icon-opacity'                     : `0.38`,

    // Hovered
    'hovered-state-layer-color'                  : Color.Primary,
    'hovered-state-layer-color-toggle-unselected': Color.Primary,
    'hovered-state-layer-color-toggle-selected'  : Color.Primary,
    'hovered-state-layer-opacity'                : State.HoveredStateLayerOpacity,
    'hovered-container-color'                    : `transparent`,
    'hovered-container-color-toggle-unselected'  : `transparent`,
    'hovered-container-color-toggle-selected'    : `transparent`,
    'hovered-label-color'                        : Color.Primary,
    'hovered-label-color-toggle-unselected'      : Color.Primary,
    'hovered-label-color-toggle-selected'        : Color.Primary,
    'hovered-icon-color'                         : Color.Primary,
    'hovered-icon-color-toggle-unselected'       : Color.Primary,
    'hovered-icon-color-toggle-selected'         : Color.Primary,

    // Focused
    'focused-state-layer-color'                  : Color.Primary,
    'focused-state-layer-color-toggle-unselected': Color.Primary,
    'focused-state-layer-color-toggle-selected'  : Color.Primary,
    'focused-state-layer-opacity'                : State.FocusedStateLayerOpacity,
    'focused-container-color'                    : `transparent`,
    'focused-container-color-toggle-unselected'  : `transparent`,
    'focused-container-color-toggle-selected'    : `transparent`,
    'focused-label-color'                        : Color.Primary,
    'focused-label-color-toggle-unselected'      : Color.Primary,
    'focused-label-color-toggle-selected'        : Color.Primary,
    'focused-icon-color'                         : Color.Primary,
    'focused-icon-color-toggle-unselected'       : Color.Primary,
    'focused-icon-color-toggle-selected'         : Color.Primary,

    // Pressed
    'pressed-state-layer-color'                  : Color.Primary,
    'pressed-state-layer-color-toggle-unselected': Color.Primary,
    'pressed-state-layer-color-toggle-selected'  : Color.Primary,
    'pressed-state-layer-opacity'                : State.PressedStateLayerOpacity,
    'pressed-container-color'                    : `transparent`,
    'pressed-container-color-toggle-unselected'  : `transparent`,
    'pressed-container-color-toggle-selected'    : `transparent`,
    'pressed-label-color'                        : Color.Primary,
    'pressed-label-color-toggle-unselected'      : Color.Primary,
    'pressed-label-color-toggle-selected'        : Color.Primary,
    'pressed-icon-color'                         : Color.Primary,
    'pressed-icon-color-toggle-unselected'       : Color.Primary,
    'pressed-icon-color-toggle-selected'         : Color.Primary,
})
