/**
 * @license
 * Copyright 2026 Kai-Orion & Sandlada
 * SPDX-License-Identifier: MIT
 *
 * @fileoverview
 * Styles for `mdc-expressive-slider` — Material Design 3 Expressive slider.
 *
 * Uses BOTH `SliderDefinitionVersion2` (base tokens) and `SliderDefinition`
 * (MD3E-specific tokens like sizes, stop indicators). The MD3E tokens
 * override the base tokens where they overlap.
 *
 * All token references use `var(--_xxx)` internal variables generated by the
 * token system.
 *
 * @link https://m3.material.io/components/sliders/specs
 */

import { Duration, Easing, Shape } from '@sandlada/mdk'
import { css, unsafeCSS } from 'lit'
import { SliderDefinition, SliderDefinitionVersion2 } from '../../component-definitions/slider.definition'
import { defineTokenRefsRecord, defineVars } from '@sandlada/jss'
import { overrideComponentTokens, stringTokens } from '../../utils/tokens'
import { ElevationDefinition } from '../../component-definitions/elevation.definition'

// Base tokens from SliderDefinitionVersion2 (label, overlap, tick marks, etc.)
const baseRecord = defineTokenRefsRecord(SliderDefinitionVersion2, {
    expandShapes: false,
    useBaseFallback: true,
    prefix: '--mdc-expressive-slider'
})

// MD3E-specific tokens (sizes, stop indicators, etc.) — override base where overlapping
const expressiveRecord = defineTokenRefsRecord(SliderDefinition, {
    expandShapes: false,
    useBaseFallback: true,
    prefix: '--mdc-expressive-slider'
})

// Merge: expressiveRecord overrides baseRecord for shared keys
const tokenRecord = { ...baseRecord, ...expressiveRecord }
const tokensStringified = unsafeCSS(defineVars(tokenRecord, true).join(''))

const medium1Duration = unsafeCSS(Duration.Medium1.ToCSSVariable())
const short2Duration = unsafeCSS(Duration.Short2.ToCSSVariable())
const emphasizedEasing = unsafeCSS(Easing.Emphasized.ToCSSVariable())

export const ExpressiveSliderStyles = [
    css`
        :host {
            ${tokensStringified};

            --_start-fraction: 0;
            --_end-fraction: 0;
            --_tick-count: 0;
            --_thumb-track-gap: 6px;

            display: inline-flex;
            vertical-align: middle;
            min-inline-size: 200px;

            ${stringTokens(overrideComponentTokens<keyof typeof ElevationDefinition>('--mdc-elevation', {
                'enabled-level': `var(--_enabled-handle-elevation)`,
                'enabled-shadow-color': `var(--_enabled-handle-shadow-color)`,
            }))};
        }

        :host([disabled]) {
            opacity: var(--_disabled-active-track-opacity);
        }

        /* ── Size presets ───────────────────────────────────────────────────── */
        :host([size='extra-small']) {
            --_track-height: var(--_extra-small-active-track-height);
            --_track-shape: var(--_extra-small-active-track-leading-shape);
            --_handle-size: var(--_extra-small-active-handle-height);
            --_icon-size: 0px;
            --_icon-padding: 0px;
            --_thumb-track-gap: 4px;
        }

        :host([size='small']) {
            --_track-height: var(--_small-active-track-height);
            --_track-shape: var(--_small-active-track-leading-shape);
            --_handle-size: var(--_small-active-handle-height);
            --_icon-size: 0px;
            --_icon-padding: 0px;
            --_thumb-track-gap: 4px;
        }

        :host([size='medium']) {
            --_track-height: var(--_medium-active-track-height);
            --_track-shape: var(--_medium-active-track-leading-shape);
            --_handle-size: var(--_medium-active-handle-height);
            --_icon-size: var(--_medium-icon-size);
            --_icon-padding: var(--_medium-icon-padding);
            --_thumb-track-gap: 6px;
        }

        :host([size='large']) {
            --_track-height: var(--_large-active-track-height);
            --_track-shape: var(--_large-active-track-leading-shape);
            --_handle-size: var(--_large-active-handle-height);
            --_icon-size: var(--_large-icon-size);
            --_icon-padding: var(--_large-icon-padding);
            --_thumb-track-gap: 8px;
        }

        :host([size='extra-large']) {
            --_track-height: var(--_extra-large-active-track-height);
            --_track-shape: var(--_extra-large-active-track-leading-shape);
            --_handle-size: var(--_extra-large-active-handle-height);
            --_icon-size: var(--_extra-large-icon-size);
            --_icon-padding: var(--_extra-large-icon-padding);
            --_thumb-track-gap: 10px;
        }

        /* ── Focus ring ─────────────────────────────────────────────────────── */
        mdc-focus-ring {
            inset: unset;
            height: var(--_handle-size);
            width: var(--_handle-size);
        }

        mdc-elevation {
            transition-duration: ${medium1Duration};
            transition-timing-function: ${emphasizedEasing};
        }

        @media (prefers-reduced-motion) {
            .label, .handle, .handleNub {
                transition-duration: 0 !important;
            }
        }

        /* ── Container ──────────────────────────────────────────────────────── */
        .container {
            flex: 1;
            display: flex;
            align-items: center;
            position: relative;
            block-size: var(--_handle-size);
            pointer-events: none;
            touch-action: none;
            user-select: none;

            --_active-track-max-clip: calc(100% - var(--_with-tick-marks-container-size) * 2);
            --_start-fraction-not-zero: min(var(--_start-fraction) * 1e9, 1);
            --_active-track-start-offset: calc(var(--_with-tick-marks-container-size) * var(--_start-fraction-not-zero));
            --_active-track-start-clip: calc(var(--_active-track-start-offset) + var(--_active-track-max-clip) * var(--_start-fraction));
            --_end-fraction-not-one: min((1 - var(--_end-fraction)) * 1e9, 1);
            --_active-track-end-offset: calc(var(--_with-tick-marks-container-size) * var(--_end-fraction-not-one));
            --_active-track-end-clip: calc(var(--_active-track-end-offset) + var(--_active-track-max-clip) * (1 - var(--_end-fraction)));

            --_clip-to-start: calc(
                var(--_handle-size) / 2 + (100% - var(--_handle-size)) *
                (var(--_start-fraction) + ((var(--_end-fraction) - var(--_start-fraction)) / 2))
            );
            --_clip-to-end: calc(100% - var(--_clip-to-start));
        }

        /* ── Track container ────────────────────────────────────────────────── */
        .track-container {
            position: absolute;
            inset: 0;
            display: flex;
            align-items: center;
            pointer-events: none;
        }

        /* ── Inactive track (full-width background) ─────────────────────────── */
        .track-inactive {
            position: absolute;
            block-size: var(--_track-height);
            border-radius: var(--_track-shape);
            background: var(--_enabled-inactive-track-color);
            inset-inline-start: 0;
            inline-size: 100%;
        }

        :host([disabled]) .track-inactive {
            background: var(--_disabled-inactive-track-color);
            opacity: var(--_disabled-inactive-track-opacity);
        }

        /* ── Active track (split around thumb with gap) ─────────────────────── */
        .track-active {
            position: absolute;
            block-size: var(--_track-height);
            border-radius: var(--_track-shape);
            background: var(--_enabled-active-track-color);
            inset-inline-start: calc(var(--_start-fraction) * 100%);
            inline-size: max(
                0%,
                (var(--_end-fraction) - var(--_start-fraction)) * 100% - var(--_thumb-track-gap) * 2
            );
            z-index: 1;
            transition: background ${medium1Duration} ${emphasizedEasing};
        }

        :host([disabled]) .track-active {
            background: var(--_disabled-active-track-color);
            opacity: var(--_disabled-active-track-opacity);
        }

        /* ── Stop indicators ────────────────────────────────────────────────── */
        .stop-indicator {
            position: absolute;
            block-size: var(--_stop-indicator-size);
            inline-size: var(--_stop-indicator-size);
            border-radius: var(--_stop-indicator-shape);
            background: var(--_enabled-active-stop-indicator-color);
            z-index: 2;
            top: 50%;
            transform: translateY(-50%);
        }

        .stop-indicator.start {
            inset-inline-start: 0;
        }

        .stop-indicator.end {
            inset-inline-end: 0;
        }

        :host([disabled]) .stop-indicator {
            background: var(--_disabled-active-stop-indicator-color);
        }

        /* ── Track icons ─────────────────────────────────────────────────────── */
        .track-container ::slotted([slot^='icon-']) {
            position: absolute;
            width: var(--_icon-size);
            height: var(--_icon-size);
            top: 50%;
            transform: translateY(-50%);
            z-index: 3;
            pointer-events: none;
        }

        .track-container ::slotted([slot='icon-start']) {
            inset-inline-start: var(--_icon-padding);
        }

        .track-container ::slotted([slot='icon-end']) {
            inset-inline-end: var(--_icon-padding);
        }

        /* ── Tick marks ─────────────────────────────────────────────────────── */
        .tickmarks {
            position: absolute;
            inset: 0;
            display: flex;
            align-items: center;
            pointer-events: none;
            background-size: calc((100% - var(--_with-tick-marks-container-size) * 2) / var(--_tick-count)) 100%;
            background-image: radial-gradient(
                circle at var(--_with-tick-marks-container-size) center,
                var(--_enabled-with-tick-marks-inactive-container-color) 0,
                var(--_enabled-with-tick-marks-inactive-container-color) calc(var(--_with-tick-marks-container-size) / 2),
                transparent calc(var(--_with-tick-marks-container-size) / 2)
            );
            --_track-padding: calc((var(--_handle-size) / 2) - var(--_with-tick-marks-container-size));
            inset-inline-start: var(--_track-padding);
            inset-inline-end: var(--_track-padding);
        }

        /* ── Handle container ───────────────────────────────────────────────── */
        .handleContainerPadded {
            position: relative;
            block-size: 100%;
            inline-size: 100%;
            padding-inline: calc(var(--_handle-size) / 2);
        }

        .handleContainerBlock {
            position: relative;
            block-size: 100%;
            inline-size: 100%;
        }

        .handleContainer {
            position: absolute;
            inset-block-start: 0;
            inset-block-end: 0;
            inset-inline-start: calc(100% * var(--_start-fraction));
            inline-size: calc(100% * (var(--_end-fraction) - var(--_start-fraction)));
        }

        /* ── Handle (thumb) ─────────────────────────────────────────────────── */
        .handle {
            position: absolute;
            block-size: var(--_handle-size);
            inline-size: var(--_handle-size);
            border-radius: var(--_handle-shape);
            display: flex;
            place-content: center;
            place-items: center;
            transition: left ${medium1Duration} cubic-bezier(0.34, 1.56, 0.64, 1);
        }

        .handleNub {
            position: absolute;
            height: var(--_track-height);
            width: var(--_handle-width);
            border-radius: var(--_handle-shape);
            background: var(--_enabled-handle-color);
            display: flex;
            align-items: center;
            justify-content: center;
            overflow: hidden;
            transition:
                width ${short2Duration} ${emphasizedEasing},
                height ${short2Duration} ${emphasizedEasing},
                background ${medium1Duration} ${emphasizedEasing};
        }

        /* Hover */
        .container > .handleContainerPadded .handle.hover > .handleNub {
            width: var(--_hovered-handle-width);
            background: var(--_hovered-handle-color);
        }

        /* Press */
        :host(:not([disabled])) {
            input.end:active ~ .handleContainerPadded .handle.end > .handleNub,
            input.start:active ~ .handleContainerPadded .handle.start > .handleNub {
                width: var(--_pressed-handle-width);
                background: var(--_pressed-handle-color);
            }
        }

        /* Focus */
        input.end:focus ~ .handleContainerPadded .handle.end > .handleNub,
        input.start:focus ~ .handleContainerPadded .handle.start > .handleNub {
            background: var(--_focused-handle-color);
        }

        :host([disabled]) .handleNub {
            background: var(--_disabled-handle-color);
            opacity: var(--_disabled-handle-opacity);
        }

        /* Handle positioning */
        .handle.start {
            inset-inline-start: calc(0px - var(--_handle-size) / 2);
        }
        .handle.end {
            inset-inline-end: calc(0px - var(--_handle-size) / 2);
        }

        .onTop {
            z-index: 1;
        }

        /* Overlap styling for range mode */
        .onTop.isOverlapping {
            .label,
            .label::before {
                outline: var(--_enabled-with-overlap-handle-outline-color) solid var(--_with-overlap-handle-outline-width);
            }
            .handleNub {
                border: var(--_enabled-with-overlap-handle-outline-color) solid var(--_with-overlap-handle-outline-width);
            }
        }

        /* ── Label (value indicator) ────────────────────────────────────────── */
        .label {
            position: absolute;
            box-sizing: border-box;
            display: flex;
            padding: 4px;
            place-content: center;
            place-items: center;
            border-radius: ${unsafeCSS(Shape.Full.ToCSSVariable())};

            color: var(--_enabled-label-text-color);
            font-family: var(--_label-text-font);
            font-size: var(--_label-text-size);
            line-height: var(--_label-text-line-height);
            font-weight: var(--_label-text-weight);

            inset-block-end: 100%;
            min-inline-size: var(--_label-container-height);
            min-block-size: var(--_label-container-height);
            background: var(--_enabled-label-container-color);
            transform-origin: center bottom;
            transform: scale(0);
            transition-property: transform;
            transition-duration: ${short2Duration};
            transition-timing-function: ${emphasizedEasing};
        }

        :host(:focus-within) .label,
        .handleContainer.hover .label,
        :where(:has(input:active)) .label {
            transform: scale(1);
        }

        .label::before,
        .label::after {
            position: absolute;
            display: block;
            content: '';
            background: inherit;
        }

        .label::before {
            --_triangle-size: calc(var(--_label-container-height) / 2);
            inline-size: var(--_triangle-size);
            block-size: var(--_triangle-size);
            bottom: calc(var(--_label-container-height) / -10);
            transform: rotate(45deg);
        }

        .label::after {
            inset: 0px;
            border-radius: inherit;
        }

        .labelContent {
            z-index: 1;
        }

        /* ── Native input styling ───────────────────────────────────────────── */
        input[type='range'] {
            opacity: 0;
            -webkit-tap-highlight-color: transparent;
            position: absolute;
            box-sizing: border-box;
            height: 100%;
            width: 100%;
            margin: 0;
            background: transparent;
            cursor: pointer;
            pointer-events: auto;
            appearance: none;
        }

        input[type='range']:focus {
            outline: none;
        }

        ::-webkit-slider-runnable-track {
            -webkit-appearance: none;
        }

        ::-moz-range-track {
            appearance: none;
        }

        ::-webkit-slider-thumb {
            -webkit-appearance: none;
            appearance: none;
            block-size: var(--_track-height);
            inline-size: var(--_handle-width);
            opacity: 0;
            z-index: 2;
        }

        ::-moz-range-thumb {
            appearance: none;
            block-size: var(--_handle-size);
            inline-size: var(--_handle-size);
            transform: scaleX(0);
            opacity: 0;
            z-index: 2;
        }

        /* Range input clipping */
        .ranged input.start {
            clip-path: inset(0 var(--_clip-to-end) 0 0);
        }
        .ranged input.start:dir(rtl) {
            clip-path: inset(0 0 0 var(--_clip-to-end));
        }
        .ranged input.end {
            clip-path: inset(0 0 0 var(--_clip-to-start));
        }
        .ranged input.end:dir(rtl) {
            clip-path: inset(0 var(--_clip-to-start) 0 0);
        }

        input.start::-webkit-slider-thumb {
            --_track-and-knob-padding: calc(
                (var(--_handle-size) - var(--_handle-width)) / 2
            );
            --_x-translate: calc(
                var(--_track-and-knob-padding) - 2 * var(--_start-fraction) *
                var(--_track-and-knob-padding)
            );
            transform: translateX(var(--_x-translate));
        }

        input.start:dir(rtl)::-webkit-slider-thumb {
            transform: translateX(calc(-1 * var(--_x-translate)));
        }

        input.end::-webkit-slider-thumb {
            --_track-and-knob-padding: calc(
                (var(--_handle-size) - var(--_handle-width)) / 2
            );
            --_x-translate: calc(
                var(--_track-and-knob-padding) - 2 * var(--_end-fraction) *
                var(--_track-and-knob-padding)
            );
            transform: translateX(var(--_x-translate));
        }

        input.end:dir(rtl)::-webkit-slider-thumb {
            transform: translateX(calc(-1 * var(--_x-translate)));
        }

        /* Ripple */
        mdc-ripple {
            border-radius: 50%;
            height: var(--_handle-size);
            width: var(--_handle-size);
        }
    `
]
