/**
 * @license
 * Copyright 2026 Kai-Orion & Sandlada
 * SPDX-License-Identifier: MIT
 */
import { describe, it, expect } from 'vitest'
import { css, CSSResult } from 'lit'
import { overrideStyleSheet } from './override-style-sheet'
import { createStyleSheet } from './create-style-sheet'

describe('overrideStyleSheet', () => {
    // Simulated multi-state component definition generated by createStyleDefinition
    const dummyButtonDefinition = {
        'enabled-container-color': '#112233',
        'hovered-container-color': '#223344',
        'pressed-container-color': '#334455',
        'focused-container-color': '#112233',
        'disabled-container-color': '#555555',
        'enabled-shape-start-start': '4px',
        'enabled-shape-start-end': '4px',
    }

    const dummyRippleDefinition = {
        'enabled-color': 'transparent',
        'hovered-color': '#000000',
        'focused-color': '#000000',
        'pressed-color': '#000000',
    }

    it('resolves base token name (e.g. shape-start-start) to matching enabled state key', () => {
        const result = overrideStyleSheet(dummyButtonDefinition, '--mdc-button', {
            'shape-start-start': '8px',
        })

        expect(result).toBeInstanceOf(CSSResult)
        expect(result.cssText).toBe('--mdc-button-enabled-shape-start-start: 8px;')
    })

    it('expands base token name with single value across all defined states in definition', () => {
        const result = overrideStyleSheet(dummyButtonDefinition, '--mdc-button', {
            'container-color': 'red',
        })

        expect(result.cssText).toContain('--mdc-button-enabled-container-color: red;')
        expect(result.cssText).toContain('--mdc-button-hovered-container-color: red;')
        expect(result.cssText).toContain('--mdc-button-pressed-container-color: red;')
        expect(result.cssText).toContain('--mdc-button-focused-container-color: red;')
        expect(result.cssText).toContain('--mdc-button-disabled-container-color: red;')
    })

    it('supports 5-state tuple overrides [enabled, hovered, pressed, focused, disabled]', () => {
        const result = overrideStyleSheet(dummyButtonDefinition, '--mdc-button', {
            'container-color': ['#111', '#222', '#333', null, '#555'],
        })

        expect(result.cssText).toContain('--mdc-button-enabled-container-color: #111;')
        expect(result.cssText).toContain('--mdc-button-hovered-container-color: #222;')
        expect(result.cssText).toContain('--mdc-button-pressed-container-color: #333;')
        expect(result.cssText).not.toContain('focused-container-color')
        expect(result.cssText).toContain('--mdc-button-disabled-container-color: #555;')
    })

    it('allows overriding specific state keys directly', () => {
        const result = overrideStyleSheet(dummyRippleDefinition, '--mdc-ripple', {
            'hovered-color': 'blue',
            'focused-color': 'cyan',
        })

        expect(result.cssText).toContain('--mdc-ripple-hovered-color: blue;')
        expect(result.cssText).toContain('--mdc-ripple-focused-color: cyan;')
        expect(result.cssText).not.toContain('enabled-color')
    })

    it('can be directly interpolated inside Lit css template literals', () => {
        const ringOverrides = overrideStyleSheet(dummyButtonDefinition, '--mdc-button', {
            'shape-start-start': '12px',
        })

        const sheet = css`
            .container {
                ${ringOverrides}
            }
        `

        expect(sheet).toBeInstanceOf(CSSResult)
        expect(sheet.cssText).toContain('.container {')
        expect(sheet.cssText).toContain('--mdc-button-enabled-shape-start-start: 12px;')
    })

    it('supports selector option wrapping', () => {
        const result = overrideStyleSheet(dummyButtonDefinition, {
            prefix: '--mdc-button',
            selector: ':host(.primary)',
        }, {
            'shape-start-start': '16px',
        })

        expect(result).toBeInstanceOf(CSSResult)
        expect(result.cssText).toBe(':host(.primary) { --mdc-button-enabled-shape-start-start: 16px; }')
    })

    it('filters out null and undefined values', () => {
        const result = overrideStyleSheet(dummyButtonDefinition, '--mdc-button', {
            'shape-start-start': '6px',
            'container-color': null,
        })

        expect(result.cssText).toBe('--mdc-button-enabled-shape-start-start: 6px;')
    })

    it('overrides child component with parent CSS variables and calculations', () => {
        const focusRingDefinition = {
            'enabled-color': '#000',
            'enabled-outward-offset': '0px',
            'enabled-shape-start-start': '2px',
        }

        const result = overrideStyleSheet(focusRingDefinition, '--mdc-focus-ring', {
            color: 'var(--_focused-indicator-color)',
            'outward-offset': 'calc((44px - var(--_enabled-container-size)) / 2)',
            'shape-start-start': 'var(--_focus-ring-shape-start-start)',
        })

        expect(result.cssText).toContain('--mdc-focus-ring-enabled-color: var(--_focused-indicator-color);')
        expect(result.cssText).toContain('--mdc-focus-ring-enabled-outward-offset: calc((44px - var(--_enabled-container-size)) / 2);')
        expect(result.cssText).toContain('--mdc-focus-ring-enabled-shape-start-start: var(--_focus-ring-shape-start-start);')
    })

    it('integrates seamlessly with createStyleSheet for multi-state parent token expansion', () => {
        const parentButtonDefinition = {
            'enabled-container-elevation': '0',
            'hovered-container-elevation': '1',
            'focused-container-elevation': '1',
            'pressed-container-elevation': '2',
            'disabled-container-elevation': '0',
        }

        const childElevationDefinition = {
            'enabled-level': '0',
        }

        const sheet = createStyleSheet(parentButtonDefinition, () => css`
            @anchor .container {
                mdc-elevation {
                    ${overrideStyleSheet(childElevationDefinition, '--mdc-elevation', {
                        level: 'var(--_container-elevation)',
                    })}
                }
            }
        `)

        const cssText = sheet.cssText
        expect(cssText).toContain('.container mdc-elevation {')
        expect(cssText).toContain('--mdc-elevation-enabled-level: var(--_enabled-container-elevation);')
        expect(cssText).toContain('.container:hover mdc-elevation {')
        expect(cssText).toContain('--mdc-elevation-enabled-level: var(--_hovered-container-elevation);')
        expect(cssText).toContain('.container:active mdc-elevation {')
        expect(cssText).toContain('--mdc-elevation-enabled-level: var(--_pressed-container-elevation);')
    })

    it('supports listing all overridden CSS variables in :host at once', () => {
        const hostStyles = css`
            :host {
                ${overrideStyleSheet(dummyRippleDefinition, '--mdc-ripple', {
                    'hovered-color': 'var(--_hovered-state-layer-color)',
                    'focused-color': 'var(--_focused-state-layer-color)',
                    'pressed-color': 'var(--_pressed-state-layer-color)',
                })}
                ${overrideStyleSheet(dummyButtonDefinition, '--mdc-focus-ring', {
                    'shape-start-start': 'var(--_focus-ring-shape-start-start)',
                })}
            }
        `

        expect(hostStyles.cssText).toContain(':host {')
        expect(hostStyles.cssText).toContain('--mdc-ripple-hovered-color: var(--_hovered-state-layer-color);')
        expect(hostStyles.cssText).toContain('--mdc-ripple-focused-color: var(--_focused-state-layer-color);')
        expect(hostStyles.cssText).toContain('--mdc-ripple-pressed-color: var(--_pressed-state-layer-color);')
        expect(hostStyles.cssText).toContain('--mdc-focus-ring-enabled-shape-start-start: var(--_focus-ring-shape-start-start);')
    })
})


