/**
 * @license
 * Copyright 2025 Kai-Orion & Sandlada
 * SPDX-License-Identifier: MIT
 */
import { Shape, State, Typescale } from '@sandlada/mdk'
import { Color } from '../utils/tokens/theme'
import { createStyleDefinition } from '../utils/tokens/create-style-definition'

/**
 * @version
 * Material Design 3 - Expressive
 */
export const SliderDefinition = createStyleDefinition({
    'extra-small-active-track-height'          : `16px`,
    'extra-small-active-track-leading-shape'   : `16px`,
    'extra-small-active-track-trailing-shape'  : `2px`,
    'extra-small-inactive-track-height'        : `16px`,
    'extra-small-inactive-track-leading-shape' : `2px`,
    'extra-small-inactive-track-trailing-shape': `16px`,
    'extra-small-active-handle-height'         : `44px`,
    'extra-small-handle-width'                 : `4px`,
    'small-active-track-height'                : `24px`,
    'small-active-track-leading-shape'         : `8px`,
    'small-active-track-trailing-shape'        : `2px`,
    'small-inactive-track-height'              : `24px`,
    'small-inactive-track-leading-shape'       : `2px`,
    'small-inactive-track-trailing-shape'      : `8px`,
    'small-active-handle-height'               : `44px`,
    'small-handle-width'                       : `4px`,
    'medium-active-track-height'               : `40px`,
    'medium-active-track-leading-shape'        : `12px`,
    'medium-active-track-trailing-shape'       : `2px`,
    'medium-inactive-track-height'             : `40px`,
    'medium-inactive-track-leading-shape'      : `2px`,
    'medium-inactive-track-trailing-shape'     : `12px`,
    'medium-active-handle-height'              : `52px`,
    'medium-handle-width'                      : `4px`,
    'large-active-track-height'                : `56px`,
    'large-active-track-leading-shape'         : `16px`,
    'large-active-track-trailing-shape'        : `2px`,
    'large-inactive-track-height'              : `56px`,
    'large-inactive-track-leading-shape'       : `2px`,
    'large-inactive-track-trailing-shape'      : `16px`,
    'large-active-handle-height'               : `68px`,
    'large-handle-width'                       : `4px`,
    'extra-large-active-track-height'          : `96px`,
    'extra-large-active-track-leading-shape'   : `28px`,
    'extra-large-active-track-trailing-shape'  : `2px`,
    'extra-large-inactive-track-height'        : `96px`,
    'extra-large-inactive-track-leading-shape' : `2px`,
    'extra-large-inactive-track-trailing-shape': `28px`,
    'extra-large-active-handle-height'         : `108px`,
    'extra-large-handle-width'                 : `4px`,
    'track-segment-gap'                        : `6px`,
    'range-handle-center-gap'                  : `6px`,
    'center-dot-size'                          : `4px`,
    'medium-icon-padding'                      : `6px`,
    'medium-icon-size'                         : `24px`,
    'large-icon-padding'                       : `6px`,
    'large-icon-size'                          : `24px`,
    'extra-large-icon-padding'                 : `8px`,
    'extra-large-icon-size'                    : `32px`,
    // Enabled
    'stop-indicator-size'                      : `4px`,
    'stop-indicator-shape'                     : Shape.Full,
    'stop-indicator-trailing-space'            : `4px`,
    'enabled-active-stop-indicator-color'              : Color.OnSecondaryContainer,
    'enabled-inactive-stop-indicator-color'            : Color.OnPrimary,
    'enabled-active-stop-indicator-container-color'    : Color.OnPrimary,
    'enabled-active-stop-indicator-container-opacity'  : `1`,
    'enabled-inactive-stop-indicator-container-color'  : Color.SecondaryContainer,
    'enabled-inactive-stop-indicator-container-opacity': `1`,
    'active-track-inner-corner-size'                   : `2px`,
    'enabled-active-track-color'                       : Color.Primary,
    'enabled-inactive-track-color'                     : Color.SecondaryContainer,
    'handle-width'                                     : `4px`,
    'active-handle-width'                              : `4px`,
    'handle-shape'                                     : Shape.Full,
    'active-handle-shape'                              : Shape.Full,
    'enabled-handle-color'                             : Color.Primary,
    'enabled-active-handle-color'                      : Color.Primary,
    'active-handle-leading-space'                      : `6px`,
    'active-handle-trailing-space'                     : `6px`,
    'active-handle-padding'                            : `6px`,
    // Disabled
    'disabled-active-stop-indicator-color'  : Color.InverseOnSurface,
    'disabled-inactive-stop-indicator-color': Color.OnSurface,
    'disabled-active-track-color'           : Color.OnSurface,
    'disabled-inactive-track-color'         : Color.OnSurface,
    'disabled-active-track-opacity'         : `0.38`,
    'disabled-inactive-track-opacity'       : `0.12`,
    'disabled-handle-color'                 : Color.OnSurface,
    'disabled-handle-opacity'               : `0.38`,
    'disabled-handle-width'                 : `4px`,
    // Hovered
    'hovered-handle-width': `4px`,
    // Focused
    'focused-active-track-color'  : Color.Primary,
    'focused-inactive-track-color': Color.SecondaryContainer,
    'focused-handle-width'        : `2px`,
    // Pressed
    'pressed-handle-color'                       : Color.Primary,
    'pressed-handle-width'                       : `2px`,
    'pressed-active-track-color'                 : Color.Primary,
    'pressed-inactive-track-color'               : Color.SecondaryContainer,
    'pressed-inactive-container-color'           : Color.InverseSurface,
    'pressed-value-indicator-label-color'        : Color.InverseOnSurface,
    'pressed-value-indicator-label-font'         : Typescale.LabelLarge.Font,
    'pressed-value-indicator-label-line-height'  : Typescale.LabelLarge.LineHeight,
    'pressed-value-indicator-label-size'         : Typescale.LabelLarge.FontSize,
    'pressed-value-indicator-label-tracking'     : Typescale.LabelLarge.Tracking,
    'pressed-value-indicator-label-weight'       : Typescale.LabelLarge.FontWeight,
    'pressed-value-indicator-active-bottom-space': `12px`,
})

/**
 * @version
 * Material Design 2
 */
export const SliderDefinitionVersion2 = createStyleDefinition({
    'enabled-active-track-color'                        : Color.Primary,
    'active-track-height'                               : `4px`,
    'active-track-shape'                                : Shape.Full,
    'disabled-active-track-color'                       : Color.OnSurface,
    'disabled-active-track-opacity'                     : `0.38`,
    'disabled-handle-color'                             : Color.OnSurface,
    'disabled-handle-elevation'                         : '0',
    'disabled-handle-opacity'                           : `0.38`,
    'disabled-inactive-track-color'                     : Color.OnSurface,
    'disabled-inactive-track-opacity'                   : `0.12`,
    'focused-handle-color'                              : Color.Primary,
    'focused-state-layer-color'                         : Color.Primary,
    'focused-state-layer-opacity'                       : State.FocusedStateLayerOpacity,
    'enabled-handle-color'                              : Color.Primary,
    'enabled-handle-elevation'                          : '1',
    'handle-height'                                     : `20px`,
    'enabled-handle-shadow-color'                       : Color.Shadow,
    'handle-shape'                                      : Shape.Full,
    'handle-width'                                      : `20px`,
    'hovered-handle-color'                              : Color.Primary,
    'hovered-state-layer-color'                         : Color.Primary,
    'hovered-state-layer-opacity'                       : State.HoveredStateLayerOpacity,
    'enabled-inactive-track-color'                      : Color.SurfaceContainerHighest,
    'inactive-track-height'                             : `4px`,
    'inactive-track-shape'                              : Shape.Full,
    'enabled-label-container-color'                     : Color.Primary,
    'enabled-label-container-elevation'                 : '0',
    'label-container-height'                            : `28px`,
    'enabled-label-text-color'                          : Color.OnPrimary,
    'label-text-font'                                   : Typescale.LabelMedium.Font,
    'label-text-line-height'                            : Typescale.LabelMedium.LineHeight,
    'label-text-size'                                   : Typescale.LabelMedium.FontSize,
    'label-text-tracking'                               : Typescale.LabelMedium.Tracking,
    'label-text-weight'                                 : Typescale.LabelMedium.FontWeight,
    'pressed-handle-color'                              : Color.Primary,
    'pressed-state-layer-color'                         : Color.Primary,
    'pressed-state-layer-opacity'                       : State.PressedStateLayerOpacity,
    'state-layer-size'                                  : `40px`,
    'enabled-track-elevation'                           : '0',
    'enabled-with-overlap-handle-outline-color'         : Color.OnPrimary,
    'with-overlap-handle-outline-width'                 : `1px`,
    'enabled-with-tick-marks-active-container-color'    : Color.OnPrimary,
    'enabled-with-tick-marks-active-container-opacity'  : `0.38`,
    'with-tick-marks-container-shape'                   : Shape.Full,
    'with-tick-marks-container-size'                    : `2px`,
    'disabled-with-tick-marks-container-color'          : Color.OnSurface,
    'disabled-with-tick-marks-container-opacity'        : `0.38`,
    'enabled-with-tick-marks-inactive-container-color'  : Color.OnSurfaceVariant,
    'enabled-with-tick-marks-inactive-container-opacity': `0.38`
})
